name = "Fido and Kitch"
default_targets = ["win32", "win64", "macos", "appimage"]
build_directory = "makelove-build"

love_files = [
    "./src/**/*.lua",
    "./lib/**/*.lua",
    "./res/**/*.tmj",
    "-*/.*",
]
