local Color = require("src.utils.color")

test("rgbToHsv: KEY_COLORS red resolves to red hue at ~full saturation and value", function()
	local h, s, v = Color.rgbToHsv(1, 0.2, 0.2)
	assertNear(0, h, 0.001)
	assertNear(0.8, s, 0.001)
	assertNear(1, v, 0.001)
end)

test("rgbToHsv: KEY_COLORS blue keeps its hue (225 deg, between cyan and blue) with full value", function()
	local h, s, v = Color.rgbToHsv(0.2, 0.4, 1)
	assertNear(0.625, h, 0.001)
	assertNear(0.8, s, 0.001)
	assertNear(1, v, 0.001)
end)

test("rgbToHsv: pure grayscale has no hue (s = 0)", function()
	local h, s, v = Color.rgbToHsv(0.5, 0.5, 0.5)
	assertEqual(0, h)
	assertEqual(0, s)
	assertEqual(0.5, v)
end)

test("rgbToHsv: black stays black, white stays white", function()
	local h, s, v = Color.rgbToHsv(0, 0, 0)
	assertEqual(0, h)
	assertEqual(0, s)
	assertEqual(0, v)

	local h2, s2, v2 = Color.rgbToHsv(1, 1, 1)
	assertEqual(0, h2)
	assertEqual(0, s2)
	assertEqual(1, v2)
end)

test("rgbToHsv: palette yellow (1, 0.9, 0.2) is an orange-yellow at hue 52.5 deg", function()
	local h, s, v = Color.rgbToHsv(1, 0.9, 0.2)
	assertNear(0.1458333, h, 0.001)
	assertNear(0.8, s, 0.001)
	assertEqual(1, v)
end)
