return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 5,
  nextobjectid = 1,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../img/backgrounds/background_night_sky.png",
      id = 2,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -512,
      offsety = 0,
      parallaxx = 0,
      parallaxy = 0,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../img/backgrounds/midground_night_mountains.png",
      id = 3,
      name = "midground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -512,
      offsety = 128,
      parallaxx = 0.5,
      parallaxy = 0.5,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../img/backgrounds/foreground_night_forest.png",
      id = 4,
      name = "foreground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -512,
      offsety = 256,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
