name: Build and Deploy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
        submodules: true
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install --assume-yes wine-stable wine64 python3-pip
    - name: Install Butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        cp butler /usr/bin
        chmod +x /usr/bin/butler
    # If you just want to use the official versions on PyPI, remove the checkout and `pip3 install makelove` instead
    - name: Checkout makelove
      uses: actions/checkout@v2
      with:
        repository: pfirsich/makelove
        path: makelove
    - name: Install makelove
      run:
        pip3 install ./makelove
        
    - name: Build
      run: cd main && python3 -m makelove
    # I have this step, so I don't need to hardcode the project name in the upload-artifact steps below
    # Sadly all of these artifacts can only be downloaded as a zip, which means that some of them will be double-zipped!
    # This is currently a limitation of GitHub Actions: https://github.com/actions/upload-artifact/issues/3
    # You could adapt these actions to unzip the zips first, but don't do that with the mac zip, because
    # the GitHub Action zipping will not preserve symlinks which would effectively break the .app!
    - name: Prepare Artifact Names
      run: |
        echo "ARTIFACT_NAME_LOVE=$(ls main/makelove-build/love | head -n1)" >> $GITHUB_ENV
        echo "ARTIFACT_NAME_APPIMAGE=$(ls main/makelove-build/appimage | head -n1)" >> $GITHUB_ENV
        echo "ARTIFACT_NAME_WIN64=$(ls main/makelove-build/win64 | head -n1)" >> $GITHUB_ENV
        echo "ARTIFACT_NAME_MACOS=$(ls main/makelove-build/macos | head -n1)" >> $GITHUB_ENV

    - uses: Butler Push
      run: |
        echo "butler push \"${{ env.ARTIFACT_NAME_WIN64 }}\" ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_ID }}:win64"
        butler push "${{ env.ARTIFACT_NAME_WIN64 }}" ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_ID }}:win64

